# -*- coding: utf-8 -*-
"""GRANIT_yandex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tbVfjglC4z5p16TeuQV5tnmsljeExQfX
"""

import pandas
# СПб Челябинск Екб Новосиб Самара Казань


path = "contacts.xlsx"
wb_obj = openpyxl.load_workbook(path)
sheet_obj = wb_obj.active


excel_data_df = pandas.read_excel('bord.xlsx')
a = excel_data_df['Страница (URL)'].tolist()

excel_data_df = pandas.read_excel('bruh.xlsx')
b = excel_data_df['Страница (URL)'].tolist()

excel_data_df = pandas.read_excel('optom.xlsx')
c = excel_data_df['Страница (URL)'].tolist()

links = a+b+c

r = 233
i = 0

while i != len(links):
  try:
    print(r)
    t = poisk(links[i], 'tel:')
    soup = str(parsing(links[i]))
    g = ""
    if t != 500000:
      t += 5
      for h in range(12):
        g += soup[t]
        t += 1
      numbers.append(g)
    else:
      numbers.append('-')
    t = poisk(links[i], 'mailto:')
    if t != 500000:
      t += 7
      k = ""
      while soup[t] != ">":
        k += soup[t]
        t += 1
      mails.append(k)
    else:
      mails.append('-')

    cell_obj = sheet_obj.cell(row = r, column = 1)    
    cell_obj.value = links[i]
    
    cell_obj = sheet_obj.cell(row = r, column = 2)    
    cell_obj.value = g
    
    cell_obj = sheet_obj.cell(row = r, column = 3)    
    cell_obj.value = k
    
    wb_obj.save("contacts.xlsx")
    r += 1
  except:
    cell_obj = sheet_obj.cell(row = r, column = 1)    
    cell_obj.value = links[i]
    
    cell_obj = sheet_obj.cell(row = r, column = 2)    
    cell_obj.value = '-'
    
    cell_obj = sheet_obj.cell(row = r, column = 3)    
    cell_obj.value = '-'

    wb_obj.save("contacts.xlsx")
    r += 1
  i += 1