# -*- coding: utf-8 -*-
"""GRANIT_google.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RgC03tJT0c1qcBQnsIHOcMG4ehPVVk0k
"""

import re
import openpyxl
from bs4 import BeautifulSoup
import requests
from urllib.request import urlopen
from lxml import html

try:
    from googlesearch import search
except ImportError:
    print("No module named 'google' found")

# to search
querys = ["Гранит Оптом Казань", "Гранитный бордюр Казань", "Гранитная брусчатка Казань"]


numbers = []
mails = []

links = []

path = "contacts.xlsx"
wb_obj = openpyxl.load_workbook(path)
sheet_obj = wb_obj.active

query = querys[2]

def parsing(link):
  url = link
  headers = {'Content-Type': 'text/html',}
  response = requests.get(url, headers=headers)
  soup = BeautifulSoup(response.text, "html.parser")
  return soup

def poisk(link, what): #это функция выводит номер, где начинается элемент what в soup  
    number = ""
    j = 24
    soup = str(parsing(link))
    where = str(re.search(what, soup))
    if re.search(what, soup) != None:
      while where[j] != ",":
        number += where[j]
        j += 1
      return int(number)
    else:
      return 500000

for j in search(query, tld="co.in", num=10, stop=250, pause=2):
    links.append(j)


r = 1
for i in range(len(links)):
  try:
    print(r)
    t = poisk(links[i], 'tel:')
    soup = str(parsing(links[i]))
    g = ""
    if t != 500000:
      t += 5
      for h in range(12):
        g += soup[t]
        t += 1
      numbers.append(g)
    else:
      numbers.append('-')
    t = poisk(links[i], 'mailto:')
    if t != 500000:
      t += 7
      k = ""
      while soup[t] != ">":
        k += soup[t]
        t += 1
      mails.append(k)
    else:
      mails.append('-')

    cell_obj = sheet_obj.cell(row = r, column = 1)    
    cell_obj.value = links[i]
    
    cell_obj = sheet_obj.cell(row = r, column = 2)    
    cell_obj.value = g
    
    cell_obj = sheet_obj.cell(row = r, column = 3)    
    cell_obj.value = k
    
    wb_obj.save("contacts.xlsx")
    r += 1
  except ConnectionError:
    cell_obj = sheet_obj.cell(row = r, column = 1)    
    cell_obj.value = links[i]
    
    cell_obj = sheet_obj.cell(row = r, column = 2)    
    cell_obj.value = '-'
    
    cell_obj = sheet_obj.cell(row = r, column = 3)    
    cell_obj.value = '-'

    wb_obj.save("contacts.xlsx")
    r += 1

# print(numbers)
# print(links)
# print(mails)